title: <p align="center"> Rajeev Ranjan </p>
logo: /assets/img/Rajeev Ranjan.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rajeev-ranjan-77354019/">LinkedIn</a> |
  <a href="https://github.com/rajeev-2">GitHub</a>
  
  <br>   
  I'm a Petroleum engineer and currently working on Data Science, Machine learning & its application in Oil & Gas industry.
 
  Worked with ONGC and Cairn India for 7 years
  Working in Kuwait Oil company for 4 years.
  <br>
  </p>



theme: jekyll-theme-minimal
